name: CLCore
main: de.craftlancer.core.CLCore
version: ${project.version}
api-version: 1.15
depend: [ Vault, WorldGuard, CLAPI ]
commands:
  convo:
    description: Used for conversations to prevent input spam.
  registerItem:
    description: Commands to access the custom item registry
  newCommandTest:
    description: Test
  clipboard:
    description: Clipboard utility to select two points for use by other plugins
  resourcepack:
    description: Commands for resource pack modification
  motd:
    description: Commands for live motd manipulation
  emojiregistry:
    description: Commands for emoji registry
permissions:
  clcore.admin:
    description: Admin permission for CLCore commands